### ISSUE TITLE
Localhost not working 

### ISSUE THREAD

**Issue by Jobians** [Mirza-Glitch/Ghostman#1]
Bro why localhost returning 404?

![Screenshot_2024-09-20-20-52-37-05_a2cf8efcdd42a8e6f7906303f104fb67](https://github.com/user-attachments/assets/0192f357-49f5-432c-93d9-c5a5c730b852)

**Comment by Mirza-Glitch** [comment]
Hey there, sorry for replying soo lately. Localhost Works perfectly fine on this extension. there must be some issue with api running on localhost. you gotta debug the issue at the api 🙃

**Comment by Jobians** [comment]
Try nextjs api

**Comment by Jobians** [comment]
Brother I don't see any need for your plugin when it can't send request to localhost 

![Screenshot_2024-10-15-20-49-02-99_a2cf8efcdd42a8e6f7906303f104fb67](https://github.com/user-attachments/assets/46145e42-59bb-4270-895c-aeffca567321)

**Comment by Mirza-Glitch** [comment]
> Brother I don't see any need for your plugin when it can't send request to localhost 
> 
> ![Screenshot_2024-10-15-20-49-02-99_a2cf8efcdd42a8e6f7906303f104fb67](https://github.com/user-attachments/assets/46145e42-59bb-4270-895c-aeffca567321)
> 

Bruh 💀

I'm extremely sorry for my late replies 👽

it might be really honor if you make sure the nextjs api is up and running. if still things don't seem right to you, please check your nextjs api with some other api testing extension (or plain javascript).

![20240921_052621.jpg](https://github.com/user-attachments/assets/4b1df226-2ba8-4b19-8afd-a34f3b3d9c5d)

**Comment by Jobians** [comment]
I think the fuck is cors issues

**Comment by Mirza-Glitch** [comment]
> I think the fuck is cors issues

might be possible. i work mostly with express js and i always use cors middleware, so never encountered such issue. still if the issue is with cors, it should show something... try your nextjs api with some other api testing tool, maybe we'll find out where the error is from
